/*
DROP TABLE [City]
DROP TABLE [Coach]
DROP TABLE [Ethnicity]
DROP TABLE [Gender]
DROP TABLE [Race]



*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = N'City')
CREATE TABLE [dbo].[City](
	[Id] [INT] NOT NULL,
	[CityName] [NVARCHAR](250) NULL,
	[CityState] [NVARCHAR](250) NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = N'Coach')
CREATE TABLE [dbo].[Coach](
	[Id] [INT] NOT NULL,
 CONSTRAINT [PK_Coach] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = N'Ethnicity')
CREATE TABLE [dbo].[Ethnicity](
	[Id] [INT] NOT NULL,
	[Ethnicity] [NVARCHAR](500) NOT NULL,
 CONSTRAINT [PK_Ethnicity] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = N'Gender')
CREATE TABLE [dbo].[Gender](
	[Id] [INT] NOT NULL,
	[Gender] [NVARCHAR](250) NULL,
 CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = N'Race')
CREATE TABLE [dbo].[Race](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Race] [NVARCHAR](50) NOT NULL,
 CONSTRAINT [PK_Race] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO