/****** Object:  Table [dbo].[City]    Script Date: 8/8/2016 4:45:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON

CREATE TABLE [dbo].[City](
	[Id] [INT] NOT NULL,
	[CityName] [NVARCHAR](250) NULL,
	[CityState] [NVARCHAR](250) NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
